from __future__ import annotations
import json
import logging
import os
import re
from .phase_checkout_checks import _read_file_via_sandbox
from .strike_tracker import StrikeVerdict
from app.orchestrator._final_checkout_utils_2 import _find_closest_name
from app.orchestrator._final_checkout_utils_3 import _extract_files_from_issue, _llm_fix_import, _write_file_to_sandbox_stub
from typing import Any, Callable, Dict, List, Optional
logger = logging.getLogger(__name__)

# v3.2-fix: Sandbox-aware filesystem checks for codebase paths.
try:
    from app.sandbox_fs import (
        sandbox_isfile as _sbx_isfile,
        sandbox_isdir as _sbx_isdir,
        sandbox_exists as _sbx_exists,
        sandbox_read_text as _sbx_read_text,
    )
    _SBX_FS_OK = True
except ImportError:
    _SBX_FS_OK = False
logger = logging.getLogger(__name__)


async def _generate_missing_file(
    rel_path: str,
    sandbox_base: str,
    sandbox_client: Any,
    original_spec: Optional[str],
    strategy: str,
    emit: Optional[Callable] = None,
) -> bool:
    """
    Generate a missing file on the sandbox.

    strategy='generate_from_spec': Use LLM with spec context.
    strategy='generate_stub': Create minimal stub (fallback).
    """
    from .final_checkout import _write_file_to_sandbox
    _emit = emit or (lambda msg: None)

    if strategy == "generate_stub":
        # Minimal stub — just enough to not break imports
        if rel_path.endswith(".py"):
            stub = f'# STUB: Auto-generated by Final Checkout\n# TODO: Implement per spec\n"""Stub for {rel_path}"""\n'
        elif rel_path.endswith("__init__.py"):
            stub = f'# Auto-generated __init__.py\n'
        else:
            stub = f'// STUB: Auto-generated by Final Checkout\n'

        return _write_file_to_sandbox(sandbox_client, rel_path, stub, sandbox_base)

    # strategy == "generate_from_spec": Use LLM
    if not original_spec:
        _emit(f"      No spec available — falling back to stub")
        return _write_file_to_sandbox_stub(sandbox_client, rel_path, sandbox_base)

    try:
        from app.providers.registry import llm_call

        prompt = (
            f"Generate the complete file content for: {rel_path}\n\n"
            f"Based on this specification:\n{original_spec[:4000]}\n\n"
            f"Output ONLY the file content, no markdown fences."
        )

        result = await llm_call(
            provider_id=os.getenv("FINAL_CHECKOUT_PROVIDER", "anthropic"),
            model_id=os.getenv("FINAL_CHECKOUT_MODEL", "claude-opus-4-6"),
            messages=[{"role": "user", "content": prompt}],
            system_prompt="You are a code generation agent. Output only file content.",
            max_tokens=int(os.getenv("FINAL_CHECKOUT_MAX_OUTPUT_TOKENS", "8000")),
            timeout_seconds=int(os.getenv("FINAL_CHECKOUT_TIMEOUT_SECONDS", "240")),
        )

        content = result.content if result else None
        if content:
            return _write_file_to_sandbox(sandbox_client, rel_path, content, sandbox_base)

        return False
    except Exception as exc:
        _emit(f"      LLM generation failed: {exc}")
        return False

async def _fix_import_resolution_issue(
    issue: Any,
    sandbox_base: str,
    sandbox_client: Any,
    verdict: StrikeVerdict,
    strategies_tried: List[str],
    emit: Optional[Callable] = None,
) -> bool:
    """
    Fix an import resolution issue.

    The provider file (file_a) is ground truth. The consumer file (file_b)
    imports a name that doesn't exist in the provider. We need to find
    the correct name and rewrite the consumer's import.

    Strike 1: Find closest match in provider exports, rewrite import.
    Strike 2: Ask LLM to fix the import with full context of both files.
    """
    from .final_checkout import _write_file_to_sandbox
    _emit = emit or (lambda msg: None)

    consumer_file = issue.file_b
    provider_file = issue.file_a

    if not consumer_file or not (_sbx_isfile(consumer_file) if _SBX_FS_OK else os.path.isfile(consumer_file)):
        # Try reading from sandbox
        if sandbox_client:
            consumer_content = _read_file_via_sandbox(
                sandbox_client, consumer_file, sandbox_base
            )
        else:
            return False
    else:
        try:
            _sbx_content = _sbx_read_text(consumer_file) if _SBX_FS_OK else None

            if _sbx_content is not None:
                consumer_content = _sbx_content

            else:

                with open(consumer_file, "r", encoding="utf-8", errors="replace") as f:
                    consumer_content = f.read()
        except Exception:
            return False

    if not consumer_content:
        return False

    # Parse what name is missing from the issue
    expected = issue.expected  # e.g. "Name 'foo' should be defined in 'bar.py'"
    import re as _re
    name_match = _re.search(r"Name '([^']+)'", expected)
    if not name_match:
        return False
    missing_name = name_match.group(1)

    # Strategy 1: Find closest match in provider
    if verdict == StrikeVerdict.PROCEED or "import_rewrite_fuzzy" not in strategies_tried:
        try:
            from .ast_helpers import get_all_defined_names
        except ImportError:
            return False

        if provider_file and (_sbx_isfile(provider_file) if _SBX_FS_OK else os.path.isfile(provider_file)):
            provider_names = get_all_defined_names(provider_file)
        elif sandbox_client and provider_file:
            provider_content = _read_file_via_sandbox(
                sandbox_client, provider_file, sandbox_base
            )
            if provider_content:
                # Extract names from content using AST
                import ast
                try:
                    tree = ast.parse(provider_content)
                    provider_names = set()
                    for node in ast.walk(tree):
                        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                            provider_names.add(node.name)
                        elif isinstance(node, ast.ClassDef):
                            provider_names.add(node.name)
                        elif isinstance(node, ast.Assign):
                            for target in node.targets:
                                if isinstance(target, ast.Name):
                                    provider_names.add(target.id)
                except SyntaxError:
                    provider_names = set()
            else:
                return False
        else:
            return False

        # Find closest match
        best_match = _find_closest_name(missing_name, provider_names)
        if best_match:
            _emit(f"    Rewriting import: '{missing_name}' -> '{best_match}' in {os.path.basename(consumer_file)}")
            new_content = consumer_content.replace(
                f"import {missing_name}", f"import {best_match}"
            ).replace(
                f"{missing_name},", f"{best_match},"
            ).replace(
                f", {missing_name}", f", {best_match}"
            )

            if new_content != consumer_content:
                return _write_file_to_sandbox(
                    sandbox_client, consumer_file, new_content, sandbox_base
                )

    # Strategy 2 (strike 2): Ask LLM
    if verdict == StrikeVerdict.CHANGE_APPROACH:
        _emit(f"    [STRIKE 2] Asking LLM to fix import in {os.path.basename(consumer_file)}")
        return await _llm_fix_import(
            consumer_file=consumer_file,
            consumer_content=consumer_content,
            provider_file=provider_file,
            missing_name=missing_name,
            sandbox_base=sandbox_base,
            sandbox_client=sandbox_client,
        )

    return False

async def _apply_ai_review_fix(
    issue: str,
    file_scope: List[str],
    sandbox_base: str,
    sandbox_client: Any,
    original_spec: Optional[str],
    strategy: str,
    emit: Optional[Callable] = None,
) -> bool:
    """
    Apply a targeted fix for a single AI review issue.

    1. Parse the issue description to identify which file(s) are affected
    2. Read those files from sandbox/host
    3. Ask LLM for a targeted fix (only the affected section)
    4. Write the fix back to sandbox

    strategy='targeted_fix' (strike 1): Fix only the specific issue.
    strategy='conservative_fix' (strike 2): Broader context, safer changes.
    """
    from .final_checkout import _write_file_to_sandbox
    _emit = emit or (lambda msg: None)

    # --- Step 1: Identify affected file(s) from the issue description ---
    affected_files = _extract_files_from_issue(issue, file_scope)
    if not affected_files:
        _emit(f"      Could not identify affected file for: {issue[:60]}")
        return False

    _emit(f"      Targeting {len(affected_files)} file(s): {', '.join(os.path.basename(f) for f in affected_files)}")

    # --- Step 2: Read file contents ---
    file_contents: Dict[str, str] = {}
    for rel_path in affected_files:
        content = None
        abs_path = os.path.join(sandbox_base, rel_path.replace("/", os.sep))

        if (_sbx_isfile(abs_path) if _SBX_FS_OK else os.path.isfile(abs_path)):
            try:
                _sbx_content = _sbx_read_text(abs_path) if _SBX_FS_OK else None

                if _sbx_content is not None:
                    content = _sbx_content

                else:

                    with open(abs_path, "r", encoding="utf-8", errors="replace") as f:
                        content = f.read()
            except Exception:
                pass

        if not content and sandbox_client:
            content = _read_file_via_sandbox(sandbox_client, abs_path, sandbox_base)

        if content:
            file_contents[rel_path] = content

    if not file_contents:
        _emit(f"      Could not read any affected files")
        return False

    # --- Step 3: Ask LLM for targeted fix ---
    try:
        from app.providers.registry import llm_call

        # Build prompt based on strategy
        if strategy == "conservative_fix":
            system = (
                "You are a careful code reviewer. Make the MINIMUM change needed "
                "to fix the issue. Do not refactor or restructure. If you are not "
                "confident in the fix, output the file unchanged."
            )
            context_cap = 6000
        else:
            system = (
                "You are a code fixer. Fix the specific issue described. "
                "Output ONLY the complete fixed file content. No explanations."
            )
            context_cap = 4000

        # Process each affected file
        any_fixed = False
        for rel_path, content in file_contents.items():
            prompt_parts = [
                f"Fix this issue in {rel_path}:\n",
                f"ISSUE: {issue}\n",
            ]

            if original_spec:
                prompt_parts.append(f"\nRELEVANT SPEC CONTEXT:\n{original_spec[:2000]}\n")

            prompt_parts.append(
                f"\nCURRENT FILE ({rel_path}):\n"
                f"```python\n{content[:context_cap]}\n```\n\n"
                f"Output ONLY the complete fixed file. No markdown fences. No explanations."
            )

            llm_result = await llm_call(
                provider_id=os.getenv("FINAL_CHECKOUT_PROVIDER", "anthropic"),
                model_id=os.getenv("FINAL_CHECKOUT_MODEL", "claude-opus-4-6"),
                messages=[{"role": "user", "content": "\n".join(prompt_parts)}],
                system_prompt=system,
                max_tokens=int(os.getenv("FINAL_CHECKOUT_MAX_OUTPUT_TOKENS", "8000")),
                timeout_seconds=int(os.getenv("FINAL_CHECKOUT_TIMEOUT_SECONDS", "240")),
            )

            fixed_content = llm_result.content if llm_result else None

            # Strip markdown fences if LLM added them despite instructions
            if fixed_content:
                fixed_content = fixed_content.strip()
                if fixed_content.startswith("```"):
                    lines = fixed_content.split("\n")
                    if lines[0].startswith("```"):
                        lines = lines[1:]
                    if lines and lines[-1].strip() == "```":
                        lines = lines[:-1]
                    fixed_content = "\n".join(lines)

            # Sanity check: must be substantial and different
            if (
                fixed_content
                and len(fixed_content) > 50
                and fixed_content != content
                and abs(len(fixed_content) - len(content)) < len(content) * 0.5
            ):
                abs_path = os.path.join(sandbox_base, rel_path.replace("/", os.sep))
                wrote = _write_file_to_sandbox(
                    sandbox_client, abs_path, fixed_content, sandbox_base
                )
                if wrote:
                    _emit(f"      Fixed {os.path.basename(rel_path)}")
                    any_fixed = True

        return any_fixed

    except Exception as exc:
        _emit(f"      LLM fix failed: {exc}")
        return False

def _parse_review_response(response: str, files_reviewed: int) -> AIReviewResult:
    """Parse the LLM review response."""
    from .final_checkout import AIReviewResult
    cleaned = response.strip()
    if cleaned.startswith("```"):
        lines = cleaned.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        cleaned = "\n".join(lines)

    cleaned = re.sub(r',\s*([}\]])', r'\1', cleaned)

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as e:
        logger.warning("[final_checkout] Failed to parse AI review: %s", e)
        return AIReviewResult(
            status="error",
            notes=f"Failed to parse review response: {e}",
            files_reviewed=files_reviewed,
        )

    overall = float(data.get("overall_score", 0))
    return AIReviewResult(
        status="pass" if overall >= 6.0 else "fail",
        overall_score=overall,
        quality_score=float(data.get("quality_score", 0)),
        security_score=float(data.get("security_score", 0)),
        performance_score=float(data.get("performance_score", 0)),
        critical_issues=data.get("critical_issues", [])[:8],
        recommendations=data.get("recommendations", [])[:8],
        files_reviewed=files_reviewed,
        notes=data.get("notes", ""),
    )
