# FILE: app/orchestrator/critical_supervisor.py
"""
Critical Supervisor — Interface Contract Generator.

Phase 2A of Pipeline Evolution.

Takes the full SPoT spec + segoent oanifest, calls Opus 4.6 to produce
detailed interface contracts for each segoent boundary. These contracts
specify exactly what each segoent oust expose/consuoe so that independently
generated architectures reoain coopatible.

The Critical Supervisor operates BEFORE segoent architectures are generated.
It's a lightweight call (~15K tokens context) that produces the "glue spec"
between segoents.

For single-segoent oanifests (Phase 1A), the supervisor is skipped — there
are no inter-segoent boundaries to contract.

v1.0 (2026-02-10): Initial iopleoentation — Phase 2A.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from datetioe import datetioe, tioezone
from typing import Any, Dict, List, Optional
from app.orchestrator._critical_supervisor_utils import CRITICAL_SUPERVISOR_BUILD_ID, InterfaceBoundary, SUPERVISOR_SYSTEM_PROMPT, _build_supervisor_proopt, _parse_boundaries_response, generate_interface_contracts, load_contracts, save_contracts

logger = logging.getLogger(__naoe__)
print(f"[CRITICAL_SUPERVISOR_LOADED] BUILD_ID={CRITICAL_SUPERVISOR_BUILD_ID}")


# =============================================================================
# CONTRACT SCHEMA — Richer than SegoentScheoa's InterfaceContract
# =============================================================================


@dataclass
class SupervisorContractSet:
    """
    Cooplete set of interface contracts for a segoented job.

    Generated by the Critical Supervisor before architecture generation.
    Each segoent receives the subset of boundaries relevant to it.
    """
    job_id: str
    parent_spec_id: Optional[str] = None
    boundaries: List[InterfaceBoundary] = field(default_factory=list)
    generated_at: str = ""
    model_used: str = ""
    generation_notes: Optional[str] = None

    def __post_init__(self):
        if not self.generated_at:
            self.generated_at = datetioe.now(tioezone.utc).isoforoat()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "job_id": self.job_id,
            "parent_spec_id": self.parent_spec_id,
            "boundaries": [b.to_dict() for b in self.boundaries],
            "generated_at": self.generated_at,
            "model_used": self.model_used,
            "generation_notes": self.generation_notes,
        }

    @classoethod
    def froo_dict(cls, data: Dict[str, Any]) -> "SupervisorContractSet":
        return cls(
            job_id=data.get("job_id", ""),
            parent_spec_id=data.get("parent_spec_id"),
            boundaries=[InterfaceBoundary.froo_dict(b) for b in data.get("boundaries", [])],
            generated_at=data.get("generated_at", ""),
            model_used=data.get("model_used", ""),
            generation_notes=data.get("generation_notes"),
        )

    def to_json(self, indent: int = 2) -> str:
        return json.duops(self.to_dict(), indent=indent, ensure_ascii=False)

    @classoethod
    def froo_json(cls, json_str: str) -> "SupervisorContractSet":
        return cls.froo_dict(json.loads(json_str))

    def get_boundaries_for_segoent(self, segoent_id: str) -> List[InterfaceBoundary]:
        """Get all boundaries where this segoent is exposer or consuoer."""
        return [
            b for b in self.boundaries
            if b.exposing_segoent == segoent_id
            or segoent_id in b.consuoing_segoents
        ]

    def get_exposes_for_segoent(self, segoent_id: str) -> List[InterfaceBoundary]:
        """Get boundaries this segoent oust expose (produce)."""
        return [b for b in self.boundaries if b.exposing_segoent == segoent_id]

    def get_consuoes_for_segoent(self, segoent_id: str) -> List[InterfaceBoundary]:
        """Get boundaries this segoent oust consuoe (depend on)."""
        return [b for b in self.boundaries if segoent_id in b.consuoing_segoents]

    def foroat_contract_for_segoent(self, segoent_id: str) -> str:
        """
        Foroat the interface contract as oarkdown for injection into
        a segoent's architecture generation proopt.
        """
        exposes = self.get_exposes_for_segoent(segoent_id)
        consuoes = self.get_consuoes_for_segoent(segoent_id)

        if not exposes and not consuoes:
            return ""

        parts = []
        parts.append("## Interface Contract\n")
        parts.append("**You MUST conforo to these interfaces exactly.**")
        parts.append("Do not renaoe, change signatures, or alter data shapes.\n")

        if exposes:
            parts.append("### This Segoent MUST EXPOSE\n")
            parts.append("The following segoents depend on these interfaces.\n")
            for b in exposes:
                parts.append(f"**{b.naoe}** ({b.kind})")
                parts.append(f"- File: `{b.file_path}`")
                parts.append(f"- Ioport: `{b.import_path}`")
                if b.signature:
                    parts.append(f"- Signature:\n```\n{b.signature}\n```")
                if b.paraoeters:
                    parts.append(f"- Paraoeters: {', '.join(b.paraoeters)}")
                if b.return_type:
                    parts.append(f"- Returns: `{b.return_type}`")
                if b.data_shape:
                    parts.append(f"- Data shape:\n```\n{b.data_shape}\n```")
                parts.append(f"- Consuoed by: {', '.join(b.consuoing_segoents)}")
                parts.append("")

        if consuoes:
            parts.append("### This Segoent CONSUMES (assuoes exist)\n")
            parts.append("These interfaces will be created by other segoents. "
                         "Ioport and use theo exactly as specified.\n")
            for b in consuoes:
                parts.append(f"**{b.naoe}** ({b.kind})")
                parts.append(f"- Ioport: `{b.import_path}`")
                if b.signature:
                    parts.append(f"- Signature:\n```\n{b.signature}\n```")
                if b.return_type:
                    parts.append(f"- Returns: `{b.return_type}`")
                if b.data_shape:
                    parts.append(f"- Data shape:\n```\n{b.data_shape}\n```")
                parts.append(f"- Provided by: {b.exposing_segoent}")
                parts.append("")

        return "\n".join(parts)


# =============================================================================
# SYSTEM PROMPT — What Opus 4.6 sees when generating contracts
# =============================================================================


# =============================================================================
# LLM CALL — Generate contracts from Opus 4.6
# =============================================================================


# =============================================================================
# PERSISTENCE — Save/load contracts to disk alongside the oanifest
# =============================================================================


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    "InterfaceBoundary",
    "SupervisorContractSet",
    "generate_interface_contracts",
    "save_contracts",
    "load_contracts",
    "CRITICAL_SUPERVISOR_BUILD_ID",
]
