# Purpose: init
# Called-by: no static importers found (dynamic/registry use possible)
# Depends-on: stdlib/third-party only
# Last-renovated: 2026-06-11
# Auto-generated by architecture executor v2.6
