from __future__ import annotations
import logging
import os
from app.overwatcher._sandbox_build_validator_utils_2 import DIAGNOSTIC_SYSTEM_PROMPT, DIAGNOSTIC_USER_PROMPT, PROJECT_UNKNOWN
from app.overwatcher._sandbox_build_validator_utils_3 import MAX_BUILD_FIX_ATTEMPTS, MAX_BUILD_OUTPUT_CHARS, _parse_diagnostic_response, _truncate_output, detect_project_from_path
from app.overwatcher.sandbox_client import SandboxClient, SandboxError
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional
logger = logging.getLogger(__name__)
logger = logging.getLogger(__name__)
SANDBOX_FRONTEND_PATH = r"C:\Orb\orb-desktop"
SANDBOX_BACKEND_PATH = r"C:\Orb\Orb"
PROJECT_VITE_REACT = "vite_react"
PROJECT_PYTHON_BACKEND = "python_backend"


BUILD_VALIDATION_TIMEOUT = int(os.getenv("OVERWATCHER_BUILD_VALIDATION_TIMEOUT", "120"))

@dataclass
class BuildFixAction:
    """A single corrective action generated by diagnostic reasoning.

    Fix types are constrained to known safe operations:
        - rewrite_file: Re-write a specific file with corrected content
        - run_command: Execute a safe sandbox command (npm install, etc.)
        - revert_file: Restore original content (placeholder for future)
    """

    fix_type: str          # "rewrite_file" | "run_command" | "revert_file"
    file_path: Optional[str] = None
    content: Optional[str] = None
    command: Optional[str] = None
    diagnosis: str = ""
    rationale: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "fix_type": self.fix_type,
            "file_path": self.file_path,
            "content_length": len(self.content) if self.content else 0,
            "command": self.command,
            "diagnosis": self.diagnosis,
            "rationale": self.rationale,
        }

@dataclass
class DiagnosticResult:
    """Result from LLM diagnostic reasoning about a build failure."""

    diagnosis: str
    root_cause: str
    fixes: List[BuildFixAction] = field(default_factory=list)
    confidence: float = 0.0
    raw_response: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "diagnosis": self.diagnosis,
            "root_cause": self.root_cause,
            "fixes": [f.to_dict() for f in self.fixes],
            "confidence": self.confidence,
        }

def detect_affected_projects(modified_files: List[str]) -> Dict[str, List[str]]:
    """Group modified files by the project they belong to.

    Args:
        modified_files: List of sandbox file paths from POT execution

    Returns:
        Dict mapping project_type -> list of file paths
    """
    projects: Dict[str, List[str]] = {}

    for fpath in modified_files:
        project_type = detect_project_from_path(fpath)
        if project_type:
            projects.setdefault(project_type, []).append(fpath)
        else:
            logger.warning(
                "[build_validator] Could not detect project for path: %s", fpath
            )

    return projects

async def detect_project_type_from_sandbox(
    client: SandboxClient,
    project_path: str,
) -> str:
    """Detect project type by probing for marker files in the sandbox.

    Args:
        client: SandboxClient instance
        project_path: Sandbox path to check

    Returns:
        Project type string
    """
    try:
        # Check for package.json → Node/Vite project
        cmd = f'Test-Path "{project_path}\\package.json"'
        result = client.shell_run(cmd, timeout_seconds=10)
        if result.stdout and "True" in result.stdout:
            return PROJECT_VITE_REACT

        # Check for pyproject.toml or setup.py → Python project
        cmd = f'(Test-Path "{project_path}\\pyproject.toml") -or (Test-Path "{project_path}\\setup.py") -or (Test-Path "{project_path}\\main.py")'
        result = client.shell_run(cmd, timeout_seconds=10)
        if result.stdout and "True" in result.stdout:
            return PROJECT_PYTHON_BACKEND

    except SandboxError as e:
        logger.warning("[build_validator] Project detection failed: %s", e)

    return PROJECT_UNKNOWN

async def validate_all_affected_projects(
    client: SandboxClient,
    modified_files: List[str],
) -> List[BuildValidationResult]:
    """Determine which projects were affected by POT execution and validate each.

    Args:
        client: SandboxClient instance
        modified_files: List of file paths written by the POT executor

    Returns:
        List of BuildValidationResult (one per affected project)
    """
    from .sandbox_build_validator import BuildValidationResult, _infer_project_path, validate_build
    if not modified_files:
        logger.info("[build_validator] No modified files — skipping validation")
        return []

    # Detect affected projects from file paths
    affected = detect_affected_projects(modified_files)

    if not affected:
        logger.warning(
            "[build_validator] Could not determine projects from paths: %s",
            modified_files,
        )
        return []

    logger.info(
        "[build_validator] Affected projects: %s",
        {k: len(v) for k, v in affected.items()},
    )

    results: List[BuildValidationResult] = []

    for project_type, files in affected.items():
        # Infer project path from actual file paths (handles host vs sandbox paths)
        project_path = _infer_project_path(project_type, files)
        if not project_path:
            logger.warning(
                "[build_validator] No sandbox path for project type: %s", project_type
            )
            continue

        result = await validate_build(
            client=client,
            project_path=project_path,
            project_type=project_type,
        )
        results.append(result)

    return results

async def diagnose_build_failure(
    *,
    llm_call_fn: Callable,
    spec_content: str,
    pot_result: Dict[str, Any],
    build_results: List[BuildValidationResult],
    attempt: int,
    max_attempts: int = MAX_BUILD_FIX_ATTEMPTS,
    previous_fixes: Optional[List[Dict]] = None,
) -> DiagnosticResult:
    """Ask the LLM to diagnose a build failure and generate a fix.

    Args:
        llm_call_fn: Async LLM call function (from overwatcher_stream)
        spec_content: Original spec content (what was intended)
        pot_result: POT execution results dict
        build_results: Failed build validation results
        attempt: Current fix attempt number (1-based)
        max_attempts: Maximum fix attempts
        previous_fixes: List of previously attempted fixes (for context)

    Returns:
        DiagnosticResult with diagnosis and fix actions
    """
    from .sandbox_build_validator import BuildValidationResult
    # Assemble evidence for the LLM
    modified_files = pot_result.get("artifacts_written", [])
    modified_files_summary = "\n".join(f"- {f}" for f in modified_files) or "None"

    # Combine build error evidence from all failed builds
    build_error_parts = []
    for br in build_results:
        if not br.passed:
            build_error_parts.append(
                f"[{br.project_type} at {br.project_path}]\n{br.error_evidence}"
            )
    build_error_output = "\n\n---\n\n".join(build_error_parts)

    # Truncate for cost control
    spec_summary = spec_content[:2000] if spec_content else "N/A"
    build_error_output = _truncate_output(build_error_output, MAX_BUILD_OUTPUT_CHARS)

    # Previous fix context
    previous_fix_summary = ""
    if previous_fixes:
        fix_descriptions = []
        for pf in previous_fixes:
            fix_descriptions.append(
                f"  - Attempt {pf.get('attempt', '?')}: {pf.get('diagnosis', 'N/A')} "
                f"(fix_type={pf.get('fix_type', 'N/A')})"
            )
        previous_fix_summary = (
            "Previous fixes attempted (did NOT resolve the issue):\n"
            + "\n".join(fix_descriptions)
        )

    # Use first failed build for details
    first_failed = next((br for br in build_results if not br.passed), None)

    user_prompt = DIAGNOSTIC_USER_PROMPT.format(
        spec_summary=spec_summary,
        modified_files_summary=modified_files_summary,
        build_error_output=build_error_output,
        project_type=first_failed.project_type if first_failed else "unknown",
        build_command=first_failed.build_command if first_failed else "N/A",
        exit_code=first_failed.exit_code if first_failed else -1,
        error_type=first_failed.error_type if first_failed else "unknown",
        affected_files=", ".join(first_failed.affected_files) if first_failed else "N/A",
        attempt=attempt,
        max_attempts=max_attempts,
        previous_fix_summary=previous_fix_summary,
    )

    logger.info(
        "[build_validator] Calling LLM for diagnostic (attempt %d/%d, prompt ~%d chars)",
        attempt, max_attempts, len(user_prompt),
    )

    # Call LLM — use the same pattern as overwatcher.py
    try:
        # Import stage_models for provider/model config
        from app.llm.stage_models import get_overwatcher_config

        config = get_overwatcher_config()

        messages = [
            {"role": "system", "content": DIAGNOSTIC_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]

        raw_result = await llm_call_fn(
            provider_id=config.provider,
            model_id=config.model,
            messages=messages,
            max_tokens=config.max_output_tokens,
        )

        raw_text = raw_result.content if hasattr(raw_result, "content") else str(raw_result)

    except Exception as e:
        logger.error("[build_validator] LLM call failed for diagnostic: %s", e)
        return DiagnosticResult(
            diagnosis=f"LLM diagnostic call failed: {e}",
            root_cause="llm_error",
            confidence=0.0,
            raw_response="",
        )

    # Parse LLM response
    return _parse_diagnostic_response(raw_text)

async def execute_all_fixes(
    client: SandboxClient,
    diagnostic: DiagnosticResult,
    inferred_frontend_path: str = SANDBOX_FRONTEND_PATH,
    inferred_backend_path: str = SANDBOX_BACKEND_PATH,
) -> List[Dict[str, Any]]:
    """Execute all fix actions from a diagnostic result.

    Args:
        client: SandboxClient instance
        diagnostic: DiagnosticResult containing fix actions
        inferred_frontend_path: Actual frontend project path
        inferred_backend_path: Actual backend project path

    Returns:
        List of execution result dicts
    """
    from .sandbox_build_validator import execute_build_fix
    results: List[Dict[str, Any]] = []

    for fix in diagnostic.fixes:
        result = await execute_build_fix(
            client, fix,
            inferred_frontend_path=inferred_frontend_path,
            inferred_backend_path=inferred_backend_path,
        )
        results.append({
            "fix_type": fix.fix_type,
            "file_path": fix.file_path,
            "command": fix.command,
            **result,
        })

        if not result["success"]:
            logger.warning(
                "[build_validator] Fix failed: %s — %s",
                fix.fix_type, result["details"],
            )
            # Continue trying other fixes (they may be independent)

    return results
