# Purpose: init
# Called-by: app.db, app.llm.spec_gate_stream, app.llm.weaver_stream_core, app.translation.gates (+5 more)
# Depends-on: stdlib/third-party only
# Last-renovated: 2026-06-11
# Auto-generated by architecture executor v2.6
