# FILE: app/sandbox/manager.py
"""Sandbox Manager: Control the zombie/clone Orb in Windows Sandbox.

This module allows Main Orb to:
1. Start its sandbox clone (backend + frontend)
2. Check clone status and health
3. Stop the clone
4. Send commands to the clone

This is a foundational piece for self-iteration - Main Orb can spawn
a test environment, run experiments, and validate changes.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from enum import Enum
from typing import Optional

logger = logging.getLogger(__name__)


class SandboxStatus(str, Enum):
    """Status of the sandbox clone."""
    UNKNOWN = "unknown"
    DISCONNECTED = "disconnected"
    STOPPED = "stopped"
    STARTING = "starting"
    RUNNING = "running"
    FULL = "full"
    ERROR = "error"


@dataclass
class SandboxHealth:
    """Health check result for sandbox."""
    status: SandboxStatus
    controller_ok: bool
    backend_ok: bool
    backend_url: str = "http://127.0.0.1:8000"
    controller_url: str = "http://192.168.250.2:8765"
    message: str = ""
    details: dict = None

    def __post_init__(self):
        if self.details is None:
            self.details = {}


# Startup script for full Orb (backend + frontend)
FULL_ORB_STARTUP_SCRIPT = r'''# Orb Full Startup Script (Auto-generated by Main Orb)
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  ZOMBIE ORB STARTING UP" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan

# Start backend in separate window
$env:ORB_MASTER_KEY = 'MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE='
Start-Process powershell -ArgumentList '-NoExit', '-Command', "cd C:\Orb\Orb; `$env:ORB_MASTER_KEY='MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE='; Write-Host 'ZOMBIE BACKEND STARTING...' -ForegroundColor Yellow; python -m uvicorn main:app --host 0.0.0.0 --port 8000"

Write-Host "Waiting for backend to initialize..." -ForegroundColor Yellow
Start-Sleep -Seconds 4

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Starting Frontend..." -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan

Set-Location C:\Orb\orb-desktop
npm run electron:dev
'''

# Backend-only startup script
BACKEND_ONLY_STARTUP_SCRIPT = r'''# Orb Backend Only (Auto-generated by Main Orb)
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  ZOMBIE ORB BACKEND STARTING" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan

cd C:\Orb\Orb
$env:ORB_MASTER_KEY = 'MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE='
python -m uvicorn main:app --host 0.0.0.0 --port 8000
'''


class SandboxManager:
    """Manager for controlling the sandbox Orb clone."""

    def __init__(self):
        self._client = None
        self._status = SandboxStatus.UNKNOWN

    @property
    def client(self):
        """Lazy-load sandbox client."""
        if self._client is None:
            from app.overwatcher.sandbox_client import get_sandbox_client
            self._client = get_sandbox_client()
        return self._client

    def check_controller(self) -> tuple[bool, Optional[dict]]:
        """Check if sandbox controller is reachable."""
        try:
            health = self.client.health()
            return True, {
                "status": health.status,
                "version": health.version,
                "repo_root": health.repo_root,
            }
        except Exception as e:
            logger.warning(f"Sandbox controller not reachable: {e}")
            return False, None

    def check_backend(self) -> tuple[bool, str]:
        """Check if Orb backend is responding in sandbox."""
        try:
            result = self.client.shell_run(
                command='(Invoke-WebRequest -Uri http://127.0.0.1:8000/ -TimeoutSec 3 -UseBasicParsing).StatusCode',
                timeout_seconds=10,
            )
            if result.ok and "200" in result.stdout:
                return True, "Backend responding (200 OK)"
            else:
                return False, result.stderr or "Backend not responding"
        except Exception as e:
            return False, str(e)

    def check_health(self) -> SandboxHealth:
        """Full health check of sandbox environment."""
        controller_ok, controller_details = self.check_controller()
        if not controller_ok:
            return SandboxHealth(
                status=SandboxStatus.DISCONNECTED,
                controller_ok=False,
                backend_ok=False,
                message="Cannot reach sandbox controller. Is Windows Sandbox running?",
            )
        backend_ok, backend_msg = self.check_backend()
        if backend_ok:
            status = SandboxStatus.RUNNING
            message = "Zombie Orb is running and responding"
        else:
            status = SandboxStatus.STOPPED
            message = "Sandbox controller is up, but Orb is not running"
        return SandboxHealth(
            status=status,
            controller_ok=True,
            backend_ok=backend_ok,
            message=message,
            details=controller_details,
        )

    def start_clone(self, full: bool = True, visible: bool = True) -> tuple[bool, str]:
        """Start the sandbox Orb clone."""
        logger.info(f"Starting sandbox clone (full={full}, visible={visible})")

        # Check controller first
        controller_ok, _ = self.check_controller()
        if not controller_ok:
            return False, "Cannot reach sandbox controller. Start Windows Sandbox first."

        # Check if already running
        backend_ok, _ = self.check_backend()
        if backend_ok:
            return True, "🧟 Zombie Orb is already running!"

        try:
            # Write startup script
            script = FULL_ORB_STARTUP_SCRIPT if full else BACKEND_ONLY_STARTUP_SCRIPT
            script_name = "start_zombie_orb.ps1"
            self.client.write_file(
                target="REPO",
                filename=script_name,
                content=script,
                overwrite=True,
            )
            logger.info(f"Wrote startup script: C:\\Orb\\{script_name}")

            # Launch it
            if visible:
                cmd = f'cmd /c start powershell -NoExit -File C:\\Orb\\{script_name}'
            else:
                cmd = f'powershell -File C:\\Orb\\{script_name}'
            result = self.client.shell_run(command=cmd, timeout_seconds=10)
            if not result.ok and result.stderr:
                return False, f"Failed to launch: {result.stderr[:200]}"

            # Wait for backend to start (longer timeout for full mode)
            max_wait = 25 if full else 12
            logger.info(f"Waiting up to {max_wait}s for backend...")
            for i in range(max_wait):
                time.sleep(1)
                backend_ok, _ = self.check_backend()
                if backend_ok:
                    self._status = SandboxStatus.RUNNING
                    return True, "🧟 Zombie Orb is now running!"

            # Backend didn't respond but process may still be starting
            self._status = SandboxStatus.STARTING
            return True, "🧟 Zombie Orb startup initiated! (Backend still initializing...)"

        except Exception as e:
            logger.error(f"Failed to start clone: {e}")
            return False, f"Error starting clone: {e}"

    def stop_clone(self) -> tuple[bool, str]:
        """Stop the sandbox Orb clone."""
        logger.info("Stopping sandbox clone...")
        controller_ok, _ = self.check_controller()
        if not controller_ok:
            return False, "Cannot reach sandbox controller"
        try:
            # Kill python processes except controller
            self.client.shell_run(
                command='Get-Process python -ErrorAction SilentlyContinue | Where-Object {$_.CommandLine -notlike "*sandbox_controller*"} | Stop-Process -Force',
                timeout_seconds=10,
            )
            # Kill electron/node
            self.client.shell_run(
                command='Get-Process node, electron -ErrorAction SilentlyContinue | Stop-Process -Force',
                timeout_seconds=10,
            )
            self._status = SandboxStatus.STOPPED
            return True, "🧟 Zombie Orb has been stopped"
        except Exception as e:
            return False, f"Error stopping clone: {e}"

    def get_status_message(self) -> str:
        """Get a human-readable status message."""
        health = self.check_health()
        if health.status == SandboxStatus.DISCONNECTED:
            return "🔴 Sandbox is not connected. Windows Sandbox may not be running."
        elif health.status == SandboxStatus.STOPPED:
            return "🟡 Sandbox is connected but Zombie Orb is not running."
        elif health.status == SandboxStatus.RUNNING:
            return "🟢 Zombie Orb is running and responding!"
        else:
            return f"⚪ Status: {health.status.value}"


# Singleton instance
_manager: Optional[SandboxManager] = None


def get_sandbox_manager() -> SandboxManager:
    """Get the singleton sandbox manager."""
    global _manager
    if _manager is None:
        _manager = SandboxManager()
    return _manager


def start_zombie_orb(full: bool = True) -> tuple[bool, str]:
    """Start the zombie Orb clone."""
    return get_sandbox_manager().start_clone(full=full)


def stop_zombie_orb() -> tuple[bool, str]:
    """Stop the zombie Orb clone."""
    return get_sandbox_manager().stop_clone()


def check_zombie_status() -> str:
    """Check and return zombie Orb status."""
    return get_sandbox_manager().get_status_message()


__all__ = [
    "SandboxStatus",
    "SandboxHealth",
    "SandboxManager",
    "get_sandbox_manager",
    "start_zombie_orb",
    "stop_zombie_orb",
    "check_zombie_status",
]
