# FILE: app/sandbox/manager.py
"""Sandbox Manager: Control the zombie/clone Orb in Windows Sandbox.

This module allows Main Orb to:
1. Start its sandbox clone (backend + frontend)
2. Check clone status and health
3. Stop the clone
4. Send commands to the clone

This is a foundational piece for self-iteration - Main Orb can spawn
a test environment, run experiments, and validate changes.
"""

from __future__ import annotations

import base64
import logging
import os
import secrets
import time
from dataclasses import dataclass
from enum import Enum
from typing import Optional

logger = logging.getLogger(__name__)


def _mint_throwaway_master_key() -> str:
    """Fresh random ORB_MASTER_KEY for each clone boot (2026-07-02).

    The sandbox DB is throwaway, so rotation is free — and the old constant
    (base64 of '0123456789…') meant every clone DB was encrypted with a
    publicly guessable key. Never a constant, never reused.
    """
    return base64.b64encode(secrets.token_bytes(32)).decode("ascii")


class SandboxStatus(str, Enum):
    """Status of the sandbox clone."""
    UNKNOWN = "unknown"
    DISCONNECTED = "disconnected"
    STOPPED = "stopped"
    STARTING = "starting"
    RUNNING = "running"
    FULL = "full"
    ERROR = "error"


@dataclass
class SandboxHealth:
    """Health check result for sandbox."""
    status: SandboxStatus
    controller_ok: bool
    backend_ok: bool
    backend_url: str = "http://127.0.0.1:8000"
    controller_url: str = "http://192.168.250.2:8765"
    message: str = ""
    details: dict = None

    def __post_init__(self):
        if self.details is None:
            self.details = {}


# Startup script for full Orb (backend + frontend).
# __ORB_MASTER_KEY__ is substituted with a FRESH random key per boot
# (see _mint_throwaway_master_key) — never a constant. The 0.0.0.0 bind is
# sandbox-internal: the host reaches the clone via the NAT IP, and the NAT
# is what keeps this off the LAN.
FULL_ORB_STARTUP_SCRIPT = r'''# Orb Full Startup Script (Auto-generated by Main Orb)
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  ZOMBIE ORB STARTING UP" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan

# Start backend in separate window (throwaway per-run master key)
$env:ORB_MASTER_KEY = '__ORB_MASTER_KEY__'
Start-Process powershell -ArgumentList '-NoExit', '-Command', "cd __BACKEND_DIR__; `$env:ORB_MASTER_KEY='__ORB_MASTER_KEY__'; Write-Host 'ZOMBIE BACKEND STARTING...' -ForegroundColor Yellow; python -m uvicorn main:app --host 0.0.0.0 --port 8000"

Write-Host "Waiting for backend to initialize..." -ForegroundColor Yellow
Start-Sleep -Seconds 4

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Starting Frontend..." -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan

Set-Location __FRONTEND_DIR__
npm run electron:dev
'''

# Backend-only startup script
BACKEND_ONLY_STARTUP_SCRIPT = r'''# Orb Backend Only (Auto-generated by Main Orb)
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  ZOMBIE ORB BACKEND STARTING" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan

cd __BACKEND_DIR__
$env:ORB_MASTER_KEY = '__ORB_MASTER_KEY__'
python -m uvicorn main:app --host 0.0.0.0 --port 8000
'''


class SandboxManager:
    """Manager for controlling the sandbox Orb clone."""

    def __init__(self):
        self._client = None
        self._status = SandboxStatus.UNKNOWN

    @property
    def client(self):
        """Lazy-load sandbox client."""
        if self._client is None:
            from app.sandbox.client import get_sandbox_client
            self._client = get_sandbox_client()
        return self._client

    def check_controller(self) -> tuple[bool, Optional[dict]]:
        """Check if sandbox controller is reachable."""
        try:
            health = self.client.health()
            return True, {
                "status": health.status,
                "version": health.version,
                "repo_root": health.repo_root,
            }
        except Exception as e:
            logger.warning(f"Sandbox controller not reachable: {e}")
            return False, None

    def check_backend(self) -> tuple[bool, str]:
        """Check if Orb backend is responding in sandbox."""
        try:
            result = self.client.shell_run(
                command='(Invoke-WebRequest -Uri http://127.0.0.1:8000/ -TimeoutSec 3 -UseBasicParsing).StatusCode',
                timeout_seconds=10,
            )
            if result.ok and "200" in result.stdout:
                return True, "Backend responding (200 OK)"
            else:
                return False, result.stderr or "Backend not responding"
        except Exception as e:
            return False, str(e)

    def check_health(self) -> SandboxHealth:
        """Full health check of sandbox environment."""
        controller_ok, controller_details = self.check_controller()
        if not controller_ok:
            return SandboxHealth(
                status=SandboxStatus.DISCONNECTED,
                controller_ok=False,
                backend_ok=False,
                message="Cannot reach sandbox controller. Is Windows Sandbox running?",
            )
        backend_ok, backend_msg = self.check_backend()
        if backend_ok:
            status = SandboxStatus.RUNNING
            message = "Zombie Orb is running and responding"
        else:
            status = SandboxStatus.STOPPED
            message = "Sandbox controller is up, but Orb is not running"
        return SandboxHealth(
            status=status,
            controller_ok=True,
            backend_ok=backend_ok,
            message=message,
            details=controller_details,
        )

    def start_clone(self, full: bool = True, visible: bool = True) -> tuple[bool, str]:
        """Start the sandbox Orb clone."""
        logger.info(f"Starting sandbox clone (full={full}, visible={visible})")

        # Check controller first
        controller_ok, _ = self.check_controller()
        if not controller_ok:
            return False, "Cannot reach sandbox controller. Start Windows Sandbox first."

        # A prior clone (healthy OR half-dead and still holding :8000/:5173)
        # must be cleared first, or the fresh boot conflicts on those ports.
        # The stop is PORT-SCOPED -- it never touches the :8765 controller.
        backend_ok, _ = self.check_backend()
        if backend_ok:
            logger.info("Clone already running; stopping it for a fresh boot")
        self._safe_stop()
        time.sleep(2)

        try:
            # Resolve the clone's real layout from the live controller -- never
            # hardcode a drive root; the sandbox reports its REPO_ROOT (e.g. D:\Orb).
            repo_root = self.client.health().repo_root.rstrip("\\/")
            backend_dir = repo_root
            frontend_dir = os.path.join(os.path.dirname(repo_root), "orb-desktop")
            script_name = "start_zombie_orb.ps1"
            script_path = os.path.join(repo_root, script_name)
            script = FULL_ORB_STARTUP_SCRIPT if full else BACKEND_ONLY_STARTUP_SCRIPT
            script = script.replace("__BACKEND_DIR__", backend_dir).replace("__FRONTEND_DIR__", frontend_dir)
            # Fresh throwaway key per boot (2026-07-02) — the constant is gone.
            script = script.replace("__ORB_MASTER_KEY__", _mint_throwaway_master_key())
            self.client.write_file(
                target="REPO",
                filename=script_name,
                content=script,
                overwrite=True,
            )
            logger.info(f"Wrote startup script: {script_path}")

            # Launch it. Start-Process returns immediately because the new
            # window owns its own handles, so the controller's synchronous,
            # output-capturing /shell/run does NOT block on the never-exiting
            # -NoExit child the way 'cmd /c start ...' did -- that hang WAS the
            # boot timeout. The readiness poll below waits for :8000.
            if visible:
                cmd = (
                    "Start-Process -FilePath powershell "
                    f"-ArgumentList '-NoExit','-NoProfile','-File','{script_path}'"
                )
            else:
                cmd = (
                    "Start-Process -FilePath powershell -WindowStyle Hidden "
                    f"-ArgumentList '-NoProfile','-File','{script_path}'"
                )
            result = self.client.shell_run(command=cmd, timeout_seconds=15)
            if not result.ok and result.stderr:
                return False, f"Failed to launch: {result.stderr[:200]}"

            # Wait for backend to start (longer timeout for full mode)
            max_wait = 25 if full else 12
            logger.info(f"Waiting up to {max_wait}s for backend...")
            for i in range(max_wait):
                time.sleep(1)
                backend_ok, _ = self.check_backend()
                if backend_ok:
                    self._status = SandboxStatus.RUNNING
                    return True, "🧟 Zombie Orb is now running!"

            # Backend didn't respond but process may still be starting
            self._status = SandboxStatus.STARTING
            return True, "🧟 Zombie Orb startup initiated! (Backend still initializing...)"

        except Exception as e:
            logger.error(f"Failed to start clone: {e}")
            return False, f"Error starting clone: {e}"

    def _safe_stop(self) -> None:
        """Best-effort teardown of a clone WITHOUT touching the :8765 controller.

        Port-scoped: kills whatever owns the clone's backend (:8000) and frontend
        (:5173), plus electron/node, all INSIDE the sandbox VM. Deliberately does
        NOT filter python by CommandLine (that property is null on PowerShell 5.1,
        which would match and kill the controller too). Mirrors the self-heal
        path's safe stop.
        """
        ps = (
            "$ErrorActionPreference='SilentlyContinue';"
            "foreach ($port in 8000,5173) {"
            " Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue |"
            " Select-Object -ExpandProperty OwningProcess -Unique |"
            " ForEach-Object { Stop-Process -Id $_ -Force -ErrorAction SilentlyContinue } };"
            "Get-Process electron,node -ErrorAction SilentlyContinue |"
            " Stop-Process -Force -ErrorAction SilentlyContinue"
        )
        try:
            self.client.shell_run(command=ps, timeout_seconds=12)
        except Exception as e:
            logger.warning(f"[sandbox] safe-stop best-effort failed: {e}")

    def stop_clone(self) -> tuple[bool, str]:
        """Stop the sandbox Orb clone."""
        logger.info("Stopping sandbox clone...")
        controller_ok, _ = self.check_controller()
        if not controller_ok:
            return False, "Cannot reach sandbox controller"
        try:
            # Kill python processes except controller
            self.client.shell_run(
                command='Get-Process python -ErrorAction SilentlyContinue | Where-Object {$_.CommandLine -notlike "*sandbox_controller*"} | Stop-Process -Force',
                timeout_seconds=10,
            )
            # Kill electron/node
            self.client.shell_run(
                command='Get-Process node, electron -ErrorAction SilentlyContinue | Stop-Process -Force',
                timeout_seconds=10,
            )
            self._status = SandboxStatus.STOPPED
            return True, "🧟 Zombie Orb has been stopped"
        except Exception as e:
            return False, f"Error stopping clone: {e}"

    def get_status_message(self) -> str:
        """Get a human-readable status message."""
        health = self.check_health()
        if health.status == SandboxStatus.DISCONNECTED:
            return "🔴 Sandbox is not connected. Windows Sandbox may not be running."
        elif health.status == SandboxStatus.STOPPED:
            return "🟡 Sandbox is connected but Zombie Orb is not running."
        elif health.status == SandboxStatus.RUNNING:
            return "🟢 Zombie Orb is running and responding!"
        else:
            return f"⚪ Status: {health.status.value}"


# Singleton instance
_manager: Optional[SandboxManager] = None


def get_sandbox_manager() -> SandboxManager:
    """Get the singleton sandbox manager."""
    global _manager
    if _manager is None:
        _manager = SandboxManager()
    return _manager


def start_zombie_orb(full: bool = True) -> tuple[bool, str]:
    """Start the zombie Orb clone."""
    return get_sandbox_manager().start_clone(full=full)


def stop_zombie_orb() -> tuple[bool, str]:
    """Stop the zombie Orb clone."""
    return get_sandbox_manager().stop_clone()


def check_zombie_status() -> str:
    """Check and return zombie Orb status."""
    return get_sandbox_manager().get_status_message()


__all__ = [
    "SandboxStatus",
    "SandboxHealth",
    "SandboxManager",
    "get_sandbox_manager",
    "start_zombie_orb",
    "stop_zombie_orb",
    "check_zombie_status",
]
