# FILE: app/llm/pipeline/critique_parts/section_authority.py
"""Block 5c: SECTION AUTHORITY VALIDATION (v1.9 - CRITIQUE DEADLOCK FIX)"""

import logging
from typing import List, Tuple

from app.llm.pipeline.critique_schemas import CritiqueIssue

logger = logging.getLogger(__name__)

# Section names that are LLM-generated suggestions, NOT user requirements.
_LLM_SUGGESTION_SECTIONS = {
    "files to modify",
    "reference files",
    "implementation steps",
    "new files to create",
    "patterns to follow",
    "patterns extracted",
    "existing patterns",
    "integration points",
    "llm architecture analysis",
    "llm analysis",
    "evidence summary",
}


def validate_section_authority(
    issues: List[CritiqueIssue],
) -> Tuple[List[CritiqueIssue], List[CritiqueIssue]]:
    """
    v1.9: Downgrade blocking issues that cite LLM-suggestion sections.
    
    These sections (Files to Modify, Implementation Steps, Reference Files, etc.)
    are implementation guidance generated by LLM analysis during SpecGate, NOT
    user requirements. The architecture is free to choose alternative approaches.
    
    Returns:
        (validated_blocking, downgraded_to_non_blocking)
    """
    if not issues:
        return [], []
    
    validated: List[CritiqueIssue] = []
    downgraded: List[CritiqueIssue] = []
    
    for issue in issues:
        spec_ref_lower = (getattr(issue, 'spec_ref', '') or '').lower()
        
        cites_suggestion_section = any(
            section in spec_ref_lower
            for section in _LLM_SUGGESTION_SECTIONS
        )
        
        if cites_suggestion_section:
            issue.severity = "non_blocking"
            downgraded.append(issue)
            print(
                f"[DEBUG] [critique] v1.9 SECTION_AUTHORITY: Downgraded {getattr(issue, 'id', 'N/A')} "
                f"— cites LLM suggestion section: {issue.spec_ref}"
            )
            logger.info(
                "[critique] v1.9 Section authority: downgraded %s — spec_ref '%s' cites LLM suggestion",
                getattr(issue, 'id', 'N/A'), issue.spec_ref
            )
        else:
            validated.append(issue)
    
    if downgraded:
        print(
            f"[DEBUG] [critique] v1.9 Section authority filter: "
            f"{len(validated)} kept, {len(downgraded)} downgraded (LLM suggestion sections)"
        )
        logger.info("[critique] v1.9 Section authority: %d kept, %d downgraded",
                    len(validated), len(downgraded))
    
    return validated, downgraded
