# FILE: app/translation/confidence_graduation.py
"""
Confidence Graduation: Promotes high-confidence Tier 1 mappings to Tier 0 rules.

When the confidence learning system has enough evidence that a phrase maps
to a specific intent (high confidence, many confirmations, zero recent
corrections), that mapping is "graduated" into a deterministic rule.

Graduated rules:
  - Cost zero per classification (no LLM call)
  - Are faster than Tier 1 (no API latency)
  - Are auditable (stored in tier0_learned_rules.py)
  - Can be manually removed if wrong

Graduation criteria (all must be met):
  - confidence >= 0.95
  - confirmations >= 10
  - corrections == 0 in last 90 days (approximated by corrections == 0)
  - Intent is NOT destructive (those always require confirmation)

Usage:
    from app.translation.confidence_graduation import (
        scan_for_graduates,
        GraduationCandidate,
    )

    candidates = scan_for_graduates()
    # Returns list of GraduationCandidate with phrase, intent, confidence
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import List, Optional

logger = logging.getLogger(__name__)


# =========================================================================
# Graduation criteria
# =========================================================================

MIN_CONFIDENCE = 0.95
MIN_CONFIRMATIONS = 10
MAX_CORRECTIONS = 0  # Zero corrections required
RECENCY_DAYS = 90    # Must have been used within 90 days

# Destructive intents are NEVER graduated (always require confirmation)
NEVER_GRADUATE_INTENTS = {
    "DELETE_FILE", "PURGE_QUARANTINE", "GIT_PUSH",
    "WIPE_DOMAIN", "RESET_STATE",
    "OVERWATCHER_EXECUTE_CHANGES",
}


@dataclass
class GraduationCandidate:
    """A confidence mapping eligible for graduation to Tier 0."""
    phrase_pattern: str
    intent: str
    confidence: float
    confirmations: int
    corrections: int
    last_used: Optional[datetime]
    record_id: int


# =========================================================================
# Scanner
# =========================================================================

def scan_for_graduates() -> List[GraduationCandidate]:
    """
    Scan the confidence_scores table for mappings eligible for graduation.

    Returns a list of GraduationCandidate objects.
    Does NOT modify any data -- caller decides what to do with results.
    """
    try:
        from app.db import get_db_session
        from app.memory.confidence_model import ConfidenceScore
    except ImportError as e:
        logger.error("[graduation] Cannot import DB models: %s", e)
        return []

    db = get_db_session()
    try:
        cutoff = datetime.utcnow() - timedelta(days=RECENCY_DAYS)

        entries = (
            db.query(ConfidenceScore)
            .filter(
                ConfidenceScore.confidence >= MIN_CONFIDENCE,
                ConfidenceScore.confirmations >= MIN_CONFIRMATIONS,
                ConfidenceScore.corrections <= MAX_CORRECTIONS,
            )
            .all()
        )

        candidates = []
        for entry in entries:
            # Skip destructive intents
            if entry.intent.upper() in NEVER_GRADUATE_INTENTS:
                continue

            # Skip if not used recently
            if entry.last_used and entry.last_used < cutoff:
                continue

            candidates.append(GraduationCandidate(
                phrase_pattern=entry.phrase_pattern,
                intent=entry.intent,
                confidence=entry.confidence,
                confirmations=entry.confirmations,
                corrections=entry.corrections,
                last_used=entry.last_used,
                record_id=entry.id,
            ))

        logger.info(
            "[graduation] Scanned %d entries, found %d candidates",
            len(entries), len(candidates),
        )
        return candidates

    except Exception as e:
        logger.error("[graduation] Scan failed: %s", e)
        return []
    finally:
        db.close()


# =========================================================================
# Rule generation
# =========================================================================

_TEMPLATE_HEADER = '''# FILE: app/translation/tier0_learned_rules.py
"""
Auto-generated graduated rules from confidence learning.

DO NOT EDIT MANUALLY -- this file is regenerated by confidence_graduation.py.
Generated: {generated_at}
Candidates graduated: {count}
"""
from __future__ import annotations

import re
from typing import Optional


class Tier0RuleResult:
    """Minimal result class (matches tier0_rules.py interface)."""
    def __init__(self, matched: bool, intent=None, confidence: float = 1.0,
                 rule_name: Optional[str] = None, reason: Optional[str] = None):
        self.matched = matched
        self.intent = intent
        self.confidence = confidence
        self.rule_name = rule_name
        self.reason = reason


# =========================================================================
# Graduated phrase->intent mappings
# =========================================================================

GRADUATED_RULES = [
'''

_TEMPLATE_FOOTER = (
    ']\n\n\n'
    'def check_graduated_rules(text: str) -> Tier0RuleResult:\n'
    '    """\n'
    '    Check input against graduated confidence rules.\n'
    '\n'
    '    These are phrase->intent mappings that have been confirmed\n'
    '    enough times with zero corrections to be trusted as Tier 0.\n'
    '    """\n'
    '    normalised = re.sub(r"\\s+", " ", text.lower().strip())\n'
    '    normalised = re.sub(r"[^\\w\\s]", "", normalised)\n'
    '\n'
    '    for phrase, intent, confirmations, confidence in GRADUATED_RULES:\n'
    '        if normalised == phrase:\n'
    '            return Tier0RuleResult(\n'
    '                matched=True,\n'
    '                intent=intent,\n'
    '                confidence=0.98,\n'
    '                rule_name="graduated_confidence",\n'
    '                reason="Graduated: " + phrase + " -> " + intent,\n'
    '            )\n'
    '\n'
    '    return Tier0RuleResult(matched=False)\n'
)


def generate_learned_rules_source(candidates: List[GraduationCandidate]) -> str:
    """
    Generate Python source code for graduated rules.

    The generated file follows the same Tier0RuleResult pattern
    as tier0_rules.py, making it a drop-in check.
    """
    header = _TEMPLATE_HEADER.format(
        generated_at=datetime.utcnow().isoformat() + "Z",
        count=len(candidates),
    )

    rule_lines = []
    for c in candidates:
        safe_phrase = c.phrase_pattern.replace("'", "\\'")
        safe_intent = c.intent.replace("'", "\\'")
        rule_lines.append(
            "    ('{phrase}', '{intent}', {confirmations}, {confidence}),  # id={rid}".format(
                phrase=safe_phrase,
                intent=safe_intent,
                confirmations=c.confirmations,
                confidence=round(c.confidence, 4),
                rid=c.record_id,
            )
        )

    return header + "\n".join(rule_lines) + "\n" + _TEMPLATE_FOOTER


def write_learned_rules(candidates: List[GraduationCandidate]) -> bool:
    """
    Write the graduated rules file.

    Returns True on success, False on failure.
    """
    import os

    source = generate_learned_rules_source(candidates)
    target_path = os.path.join(
        os.path.dirname(__file__), "tier0_learned_rules.py"
    )

    try:
        with open(target_path, "w", encoding="utf-8") as f:
            f.write(source)
        logger.info(
            "[graduation] Wrote %d graduated rules to %s",
            len(candidates), target_path,
        )
        return True
    except Exception as e:
        logger.error("[graduation] Failed to write rules: %s", e)
        return False


# =========================================================================
# Full graduation pipeline
# =========================================================================

def run_graduation() -> int:
    """
    Run the full graduation pipeline:
    1. Scan for eligible candidates
    2. Generate and write the learned rules file
    3. Return count of graduated rules

    Safe to call repeatedly -- idempotent.
    """
    candidates = scan_for_graduates()

    if not candidates:
        logger.info("[graduation] No candidates eligible for graduation")
        # Still write an empty file so the import doesn't fail
        write_learned_rules([])
        return 0

    success = write_learned_rules(candidates)
    if success:
        logger.info("[graduation] Graduated %d rules", len(candidates))
        return len(candidates)
    else:
        return 0


__all__ = [
    "GraduationCandidate",
    "scan_for_graduates",
    "run_graduation",
    "write_learned_rules",
    "generate_learned_rules_source",
]
