# FILE: app/translation/tier0_learned_rules.py
"""
Auto-generated graduated rules from confidence learning.

DO NOT EDIT MANUALLY -- this file is regenerated by confidence_graduation.py.
Generated: 2026-02-26T09:56:27.240097Z
Candidates graduated: 0
"""
from __future__ import annotations

import re
from typing import Optional


class Tier0RuleResult:
    """Minimal result class (matches tier0_rules.py interface)."""
    def __init__(self, matched: bool, intent=None, confidence: float = 1.0,
                 rule_name: Optional[str] = None, reason: Optional[str] = None):
        self.matched = matched
        self.intent = intent
        self.confidence = confidence
        self.rule_name = rule_name
        self.reason = reason


# =========================================================================
# Graduated phrase->intent mappings
# =========================================================================

GRADUATED_RULES = [

]


def check_graduated_rules(text: str) -> Tier0RuleResult:
    """
    Check input against graduated confidence rules.

    These are phrase->intent mappings that have been confirmed
    enough times with zero corrections to be trusted as Tier 0.
    """
    normalised = re.sub(r"\s+", " ", text.lower().strip())
    normalised = re.sub(r"[^\w\s]", "", normalised)

    for phrase, intent, confirmations, confidence in GRADUATED_RULES:
        if normalised == phrase:
            return Tier0RuleResult(
                matched=True,
                intent=intent,
                confidence=0.98,
                rule_name="graduated_confidence",
                reason="Graduated: " + phrase + " -> " + intent,
            )

    return Tier0RuleResult(matched=False)
