# FILE: app/pipeline_v2/host_launcher.py
# Purpose: live12 — every external host build ships a double-clickable Launch.bat at project root.
# Called-by: app.pipeline_v2.orchestrator (external host app lane)
# Depends-on: app.pipeline_v2.verifier_agent.host_perception
# Last-renovated: 2026-07-05
"""Taz's standing requirement (2026-07-05): every build must leave something
at the top of the project folder that launches the app on a double-click.

Deterministic, not prompted: after a successful external-host build the
orchestrator calls ensure_launcher(), which resolves the entrypoint with the
same logic the eyes use (guess_entrypoint — so the launcher and the checkout
can never disagree about what "the app" is) and writes Launch.bat at the
project root. Overwritten every build; `|| pause` keeps a crashing app's
traceback on screen instead of a vanishing console window.
"""

from __future__ import annotations

import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)

LAUNCHER_NAME = "Launch.bat"

_TEMPLATE = """@echo off
rem Auto-generated by ASTRA ({project_name}) — double-click to play.
cd /d "%~dp0"
"{python}" "{entry}" || pause
"""


def ensure_launcher(project_root: str, project_name: str = "") -> Optional[str]:
    """Write Launch.bat at the project root. Returns its path, or None when
    no entrypoint could be resolved (nothing worth launching yet)."""
    try:
        from app.pipeline_v2.verifier_agent.host_perception import guess_entrypoint
        cmd = guess_entrypoint(project_root)
        if not cmd or len(cmd) < 2:
            logger.warning("[host_launcher] no entrypoint under %s — launcher skipped", project_root)
            return None
        python_exe, entry = cmd[0], cmd[1]
        out = os.path.join(project_root, LAUNCHER_NAME)
        content = _TEMPLATE.format(
            project_name=project_name or os.path.basename(project_root),
            python=python_exe,
            entry=entry,
        )
        with open(out, "w", encoding="utf-8", newline="\r\n") as fh:
            fh.write(content)
        logger.info("[host_launcher] wrote %s -> %s", out, entry)
        return out
    except Exception as exc:
        logger.warning("[host_launcher] launcher write failed: %s", exc)
        return None


__all__ = ["ensure_launcher", "LAUNCHER_NAME"]
